"""Unit tests for the meeting-transcript ingester.

Everything is exercised against temp files; no provider APIs or network.
"""
import json

import pytest

VTT = """WEBVTT

1
00:00:01.000 --> 00:00:04.000
Jon: morning, let's start with the close

2
00:00:04.500 --> 00:00:08.000
Marie: AP is clean, AR has two stragglers
"""


class TestParseCaptions:
    def test_cues_become_timestamped_rows(self, mti):
        assert mti.parse_captions(VTT) == [
            "[00:00:01] Jon: morning, let's start with the close",
            "[00:00:04] Marie: AP is clean, AR has two stragglers",
        ]

    def test_srt_comma_milliseconds_are_handled(self, mti):
        srt = "1\n00:01:02,500 --> 00:01:05,000\nhello\n"
        assert mti.parse_captions(srt) == ["[00:01:02] hello"]

    def test_short_mmss_timestamps_are_handled(self, mti):
        assert mti.parse_captions("00:05.000 --> 00:09.000\nhi\n") == ["[00:05] hi"]

    def test_duplicate_consecutive_cues_are_dropped(self, mti):
        text = "00:00:01.000 --> 00:00:02.000\nsame\n\n00:00:01.000 --> 00:00:02.000\nsame\n"
        assert mti.parse_captions(text) == ["[00:00:01] same"]

    def test_notes_and_styles_are_skipped(self, mti):
        text = "WEBVTT\n\nNOTE generated by zoom\nSTYLE\n\n00:00:01.000 --> 00:00:02.000\nhi\n"
        assert mti.parse_captions(text) == ["[00:00:01] hi"]

    def test_untimed_text_is_kept_verbatim(self, mti):
        assert mti.parse_captions("just a line\n") == ["just a line"]


class TestParseJsonExport:
    def test_transcript_rows_and_metadata(self, mti):
        rows, meta = mti.parse_json_export({
            "title": "Q3 close review",
            "date": "2026-08-30T15:00:00Z",
            "participants": [{"name": "Jon"}, "Marie"],
            "recording_url": "https://granola.example/abc",
            "transcript": [
                {"speaker": "Jon", "start_time": "00:00:01", "text": "kick off"},
                {"speaker": "Marie", "text": "AP is clean"},
                {"text": ""},
            ],
        })
        assert rows == ["[00:00:01] Jon: kick off", "Marie: AP is clean"]
        assert meta == {
            "title": "Q3 close review",
            "date": "2026-08-30",
            "participants": ["Jon", "Marie"],
            "recording_url": "https://granola.example/abc",
        }

    @pytest.mark.parametrize("key", ["segments", "sentences", "utterances"])
    def test_alternate_array_keys(self, mti, key):
        rows, _ = mti.parse_json_export({key: [{"text": "hello"}]})
        assert rows == ["hello"]

    def test_plain_string_segments(self, mti):
        rows, _ = mti.parse_json_export({"transcript": ["one", "two"]})
        assert rows == ["one", "two"]

    def test_missing_transcript_array_exits(self, mti, capsys):
        with pytest.raises(SystemExit):
            mti.parse_json_export({"title": "no body"})
        assert "transcript" in json.loads(capsys.readouterr().out)["error"]


class TestInference:
    def test_provider_from_path(self, mti):
        assert mti.guess_provider("/tmp/granola-export.vtt") == "Granola"
        assert mti.guess_provider("/tmp/Zoom_recording.vtt") == "Zoom"
        assert mti.guess_provider("/tmp/whatever.vtt") == "unknown"

    def test_explicit_provider_wins(self, mti):
        assert mti.guess_provider("/tmp/zoom.vtt", "Fireflies") == "Fireflies"

    def test_date_from_filename(self, mti):
        assert mti.guess_date("/tmp/2026-08-30-standup.vtt") == "2026-08-30"
        assert mti.guess_date("/tmp/20260830_standup.vtt") == "2026-08-30"

    def test_date_falls_back_to_mtime(self, mti, tmp_path):
        f = tmp_path / "standup.vtt"
        f.write_text("x")
        assert mti.guess_date(str(f)) == mti.date_cls.fromtimestamp(f.stat().st_mtime).isoformat()

    def test_title_from_markdown_heading(self, mti):
        assert mti.guess_title("/tmp/x.md", None, "# Q3 Close Review\n\nbody") == "Q3 Close Review"

    def test_title_from_filename_without_date(self, mti):
        assert mti.guess_title("/tmp/2026-08-30-jon-marie-sync.vtt") == "jon marie sync"

    def test_slugify(self, mti):
        assert mti.slugify("Q3 Close Review — AP/AR!") == "q3-close-review-ap-ar"


class TestReadExport:
    def test_vtt_dispatch(self, mti, tmp_path):
        f = tmp_path / "2026-08-30-close.vtt"
        f.write_text(VTT)
        rows, meta = mti.read_export(str(f))
        assert rows[0].startswith("[00:00:01]") and meta == {}

    def test_markdown_kept_verbatim(self, mti, tmp_path):
        f = tmp_path / "notes.md"
        f.write_text("# Sync\n\nJon: hello\n")
        rows, _ = mti.read_export(str(f))
        assert rows == ["# Sync", "", "Jon: hello"]

    def test_empty_file_exits(self, mti, tmp_path):
        f = tmp_path / "empty.vtt"
        f.write_text("   ")
        with pytest.raises(SystemExit):
            mti.read_export(str(f))

    def test_invalid_json_exits(self, mti, tmp_path):
        f = tmp_path / "bad.json"
        f.write_text("{nope}")
        with pytest.raises(SystemExit):
            mti.read_export(str(f))


class TestBuildNote:
    def test_frontmatter_and_body(self, mti):
        note = mti.build_note(
            ["Jon: hello"],
            title="Q3 close",
            date="2026-08-30",
            provider="Granola",
            source="Granola — /tmp/x.vtt",
            participants=["Jon", "Marie"],
            recording_url=None,
        )
        assert note.startswith("---\nsource: Granola — /tmp/x.vtt\n")
        assert "date: 2026-08-30" in note
        assert "participants: [Jon, Marie]" in note
        assert "recording_url: null" in note
        assert "type: meeting-transcript" in note
        assert note.rstrip().endswith("Jon: hello")


class TestUniquePath:
    def test_existing_note_is_not_clobbered(self, mti, tmp_path):
        first = tmp_path / "2026-08-30 close.md"
        first.write_text("original")
        assert mti.unique_path(first).name == "2026-08-30 close-2.md"

    def test_free_path_is_returned_unchanged(self, mti, tmp_path):
        p = tmp_path / "new.md"
        assert mti.unique_path(p) == p


class TestMain:
    def test_end_to_end_writes_into_the_transcript_area(self, mti, tmp_path, monkeypatch, capsys):
        export = tmp_path / "2026-08-30-granola-close-review.vtt"
        export.write_text(VTT)
        vault = tmp_path / "vault"
        monkeypatch.setattr(
            mti.sys, "argv",
            ["ingest_meeting_transcript.py", str(export), "--vault-root", str(vault)],
        )
        mti.main()

        summary = json.loads(capsys.readouterr().out)
        written = (
            tmp_path / "vault" / mti.TRANSCRIPT_AREA / "2026-08-30 granola-close-review.md"
        )
        assert summary["written_to"] == str(written)
        assert summary["provider"] == "Granola"
        assert summary["lines"] == 2
        assert "Jon: morning" in written.read_text()

    def test_missing_destination_flags_exit(self, mti, tmp_path, monkeypatch):
        export = tmp_path / "x.vtt"
        export.write_text(VTT)
        monkeypatch.setattr(mti.sys, "argv", ["ingest_meeting_transcript.py", str(export)])
        with pytest.raises(SystemExit):
            mti.main()
